### ISSUE TITLE
Support arrow keys in Team Arena UI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zturtleman/ioq3ztm#26]
```
Merge arrow key support for Team Arena UI from Turtle Arena.

See "#ifdef IOQ3ZTM // ARROWS" and the like.

(Look into including in ioq3 as well.)
```

Original issue reported on code.google.com by `ZTurtleMan` on 17 Sep 2012 at 7:06

**Comment by rawr51919** [comment]
Arrow keys work for navigating the TA menu in Spearmint, so go ahead and close this, @zturtleman.

**Comment by zturtleman** [comment]
Merge arrow key support for Team Arena UI from Turtle Arena in https://github.com/zturtleman/mint-arena/commit/a44777e3b9aba0e0859ab7813350c0960fbe5697.
